In [1]:
import numpy as np


In [3]:


array = np.arange(1, 21, 3)
print(array)


[ 1  4  7 10 13 16 19]


In [5]:
array = np.random.rand(3)
print(array)

[0.51585038 0.92438278 0.01351429]


In [7]:
arr = np.array([[10, 20, 45],
                [30, 12, 16],
                [42, 17, 56]])

# Slice to get the first two rows
first_two_rows = arr[:2, :]
print("First two rows:")
print(first_two_rows)

# Slice to get the last two rows
last_two_rows = arr[1:, :]
print("\nLast two rows:")
print(last_two_rows)

First two rows:
[[10 20 45]
 [30 12 16]]

Last two rows:
[[30 12 16]
 [42 17 56]]


In [9]:

# Create two 2x2 arrays
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

print("Array A:\n", a)
print("Array B:\n", b)

# Vertical stacking (rows on top of each other)
v_stack = np.vstack((a, b))
print("\nVertically Stacked:\n", v_stack)

# Horizontal stacking (columns side by side)
h_stack = np.hstack((a, b))
print("\nHorizontally Stacked:\n", h_stack)

# Splitting: Split the vertical stack into 2 arrays (axis=0)
split_v = np.vsplit(v_stack, 2)
print("\nSplit Vertically:")
for i, s in enumerate(split_v):
    print(f"Part {i+1}:\n{s}")

# Splitting: Split the horizontal stack into 2 arrays (axis=1)
split_h = np.hsplit(h_stack, 2)
print("\nSplit Horizontally:")
for i, s in enumerate(split_h):
    print(f"Part {i+1}:\n{s}")


Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6]
 [7 8]]

Vertically Stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally Stacked:
 [[1 2 5 6]
 [3 4 7 8]]

Split Vertically:
Part 1:
[[1 2]
 [3 4]]
Part 2:
[[5 6]
 [7 8]]

Split Horizontally:
Part 1:
[[1 2]
 [3 4]]
Part 2:
[[5 6]
 [7 8]]


In [11]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Shape and number of dimensions of x
print("Shape of x:", x.shape)
print("Number of dimensions of x:", x.ndim)

# Reshape x to a (3,1) matrix
x_reshaped = x.reshape(3, 1)
print("\nReshaped x to (3,1):\n", x_reshaped)
print("New number of dimensions of x:", x_reshaped.ndim)

# Reshape y to a (3,1) matrix and find number of dimensions
y_reshaped = y.reshape(3, 1)
print("\nReshaped y to (3,1):\n", y_reshaped)
print("Number of dimensions of y after reshaping:", y_reshaped.ndim)

Shape of x: (3,)
Number of dimensions of x: 1

Reshaped x to (3,1):
 [[ 2]
 [-1]
 [-8]]
New number of dimensions of x: 2

Reshaped y to (3,1):
 [[ 3]
 [ 1]
 [-2]]
Number of dimensions of y after reshaping: 2
